name: UI Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      #Закомментировать перед первым запуском и раскоментировать при последующих
      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run UI-tests via docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGIN2: ${{ secrets.LOGIN2 }}
          PASSWORD2: ${{ secrets.PASSWORD2 }}
        run: |
          docker-compose up --exit-code-from regression || true 
      #Закомментировать перед первым запуском и раскоментировать при последующих
      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history
          sudo cp -R ./.github/gh-pages/history/* allure-results/history/

      - name: Generate Allure report
        run: |
          sudo docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"
      #Закомментировать перед первым запуском и раскоментировать при последующих
      - name: Update Allure history
        run: |
          sudo cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }} #CI_TOKEN генерируется в основных настройках и затем добавляется в сикреты репы
          branch: gh-pages
          folder: allure-report
          clean: true